routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::middleware(['auth'])->group(function (){
  Route::resource('companies', 'CompaniesController');
  Route::get('projects/create/{company_id?}', 'ProjectsController@create');
  Route::post('projects/adduser', 'ProjectsController@adduser')->name('projects.adduser');
  Route::resource('projects', 'ProjectsController');

  Route::resource('roles', 'RolesController');
  Route::resource('tasks', 'TasksController');
  Route::resource('users', 'UsersController');
  Route::resource('comments', 'CommentsController');
});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
  protected $fillable = [
      'name',
      'description',
      'company_id',
      'user_id',
      'days',
  ];
  public function users()
  {
    return $this->belongsToMany('App\User');
  }
  public function company()
  {
    return $this->belongsTo('App\Company');
  }
  public function comments()
  {
    return $this->morphMany('App\Comment', 'commentable');
  }
}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use App\Project;
use App\Company;
use App\User;
use App\ProjectUser;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ProjectsController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    //
    if (Auth::check()) {
      $projects = Project::where('user_id', Auth::user()->id)->get();

      return view('projects.index', ['projects'=>$projects]);
    }
      return view('auth.login');
  }

public function adduser(Request $request)
{
  // add user to project function
 // take a project add a user to it;
$project = Project::find($request->input('project_id'));


 if (Auth::user()->id == $project->user_id) {


   $user = User::where('email', $request->input('email'))->first();

   //check if user is already added
   $projectUser = ProjectUser::where('user_id', $user->id)
                               ->where('project_id', $project->id)
                               ->first();
if ($projectUser) {
  //if user already exists
  return redirect()->route('projects.show', ['project'=>$project->id])
  ->with('success', $request->input('email').' already a member of this project');
}


   if ($user && $project) {
     $project->users()->attach($user->id);
     return redirect()->route('projects.show', ['project'=>$project->id])->with('success', $request->input('email').' added successfully to project');
   }
 }
return redirect()->route('projects.show', ['project'=>$project->id])->with('errors', ' error adding user');



}

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create($company_id = null)
  {
    $companies = null;
    if (!$company_id) {
        $companies = Company::where('user_id', Auth::user()->id)->get();
    }
      return view('projects.create',['company_id'=>$company_id, 'companies'=>$companies]);

  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    if(Auth::check()){
         $project = Project::create([
             'name' => $request->input('name'),
             'description' => $request->input('description'),
             'company_id' => $request->input('company_id'),
             'user_id' => Auth::user()->id
         ]);
         if($project){
             return redirect()->route('projects.show', ['project'=> $project->id])
             ->with('success' , 'Project created successfully');
         }
     }

         return back()->withInput()->with('errors', 'Error creating new project');
  }


  /**
   * Display the specified resource.
   *
   * @param  \App\Project  $project
   * @return \Illuminate\Http\Response
   */
  public function show(Project $project)
  {
      //
       //$project = Project::where('id', $project->id)->first(); //query method one
       $project = Project::find($project->id);

       $comments = $project->comments;

      return view('projects.show', ['project'=>$project, 'comments'=> $comments]);
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  \App\Project  $project
   * @return \Illuminate\Http\Response
   */
  public function edit(Project $project)
  {
      //
      $project = Project::find($project->id);

     return view('projects.edit', ['project'=>$project]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  \App\Project  $project
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, Project $project)
  {
      //save data
      $projectUpdate = Project::where('id', $project->id)
      ->update([
        'name'=> $request->input('name'),
        'description'=> $request->input('description')
      ]);

      if ($projectUpdate) {
      return redirect()->route('projects.show',['project'=>$project->id])->with('success', 'Project updated succesfully');
      }
      // redirect
       return back()->withInput();
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  \App\Project  $project
   * @return \Illuminate\Http\Response
   */
  public function destroy(Project $project)
  {
    $findProject = Project::find( $project->id);
if($findProject->delete()){

        //redirect
        return redirect()->route('projects.index')
        ->with('success' , 'Project deleted successfully');
    }
    return back()->withInput()->with('error' , 'Project could not be deleted');

  }
}

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('content')
  <div class="col-md-9 col-lg-9 col-sm-9 pull-left" style="background: white;">
    <h1>Create new Project</h1>
      <!-- Example row of columns -->
      <div class="row col-md-12 col-lg-12 col-sm-12" >

            <form action="{{route('projects.store')}}" method="post">
                  {{ csrf_field() }}
                  <div class="form-group">
                    <label for="project-name">Name<span class="required">*</label>
                    <input placeholder="Enter a Name"
                           id="project-name"
                           required
                           name="name"
                           spellcheck="false"
                           class="form-control"
                                        />

                                        @if ($companies != null)
                    <input type="hidden"
                            class="form-control"
                           name="company_id"
                           value="{{$company_id}}"
                                        />
                                        @endif



                  </div>
                  @if ($companies != null)


                  <div class="form-group">
                    <label for="company-content">Select Company</label>
                    <select class="form-control" name="company_id">
                      @foreach ($companies as $company)
                        <option value="{{$company->id}}">{{$company->name}}</option>
                      @endforeach


                    </select>
                  </div>
                  @endif
                  <div class="form-group">
                    <label for="project-content">Description</label>
                    <textarea  placeholder="Enter a Description"
                               style="resize: vertical"
                               id="project-content"
                               name="description"
                               rows="5"
                               spellcheck="false"
                               class="form-control autosize-target text-left"
                               />
                    </textarea>
                  </div>
                  <div class="form-group">
                    <input type="submit" class="btn btn-primary">
                  </div>
            </form>


      </div>
        </div>
        <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
          {{-- <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div> --}}
          <div class="sidebar-module">
            <h4>Actions</h4>
            <ol class="list-unstyled">
              <li><a href="/projects">My projects</a></li>
            </ol>
          </div>

          {{-- <div class="sidebar-module">
            <h4>Users</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li>
            </ol>
          </div> --}}
        </div>
    @endsection

resources/views/projects/edit.blade.php
@extends('layouts.app')

@section('content')
  <div class="col-md-9 col-lg-9 col-sm-9 pull-left">
      <!-- Example row of columns -->
      <div class="row col-md-12 col-lg-12 col-sm-12" style="background: white; margin:10px;">
            <form action="{{route('companies.update',[$company->id])}}" method="post">
                  {{ csrf_field() }}
                  <input type="hidden" name="_method" value="put">
                  <div class="form-group">
                    <label for="company-name">Name<span class="required">*</label>
                    <input placeholder="Enter a Name"
                           id="company-name"
                           required
                           name="name"
                           spellcheck="false"
                           class="form-control"
                           value="{{$company->name}}"
                                        />
                  </div>
                  <div class="form-group">
                    <label for="company-content">Description</label>
                    <textarea  placeholder="Enter a Description"
                               style="resize: vertical"
                               id="company-content"
                               name="description"
                               rows="5"
                               spellcheck="false"
                               class="form-control autosize-target text-left"
                               />{{ $company->description }}
                    </textarea>
                  </div>
                  <div class="form-group">
                    <input type="submit" class="btn btn-primary">
                  </div>
            </form>


      </div>
        </div>
        <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
          {{-- <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div> --}}
          <div class="sidebar-module">
            <h4>Actions</h4>
            <ol class="list-unstyled">
              <li><a href="/companies/{{$company->id}}">View Companies</a></li>
              <li><a href="/companies/">All Companies</a></li>

            </ol>
          </div>

          {{-- <div class="sidebar-module">
            <h4>Users</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li>
            </ol>
          </div> --}}
        </div>
    @endsection

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('content')

<div class="col-md-6 col-lg-6 col-md-offset-3  col-lg-offset-3">
    <div class="panel panel-primary ">
      <br>
    <div class="panel-heading">Projects<a  class="pull-right btn btn-primary btn-sm" href="/projects/create">
      <br>
    <i class="fa fa-plus-square" aria-hidden="true"></i>  Create new</a> </div>
    <div class="panel-body">


    <ul class="list-group">
    @foreach($projects as $project)
        <li class="list-group-item">
        <i class="fa fa-play" aria-hidden="true"></i> <a href="/projects/{{ $project->id }}" >  {{ $project->name }}</a></li>
    @endforeach
    </ul>


    </div>
    </div>
</div>

@endsection

resources/views/projects/show.blade.php
@extends('layouts.app')

@section('content')
  <div class="col-md-9 col-lg-9 col-sm-9 pull-left">



      <div class="jumbotron">
        <h1>{{$project->name}}</h1>
        <p class="lead">{{$project->description}}</p>
        {{-- <p><a class="btn btn-lg btn-success" href="#" role="button">Get started today</a></p> --}}
      </div>


      <!-- Example row of columns -->
      <div class="row col-md-12 col-lg-12 col-sm-12" style="background: white; margin:10px;">
        {{-- <a href="/projects/create" class="pull-right btn btn-primary btn-sm">Add a Project</a> --}}

              <br>
              @include('partials.comments')

              <div class="row container-fluid">



                <form method="post" action="{{ route('comments.store') }}">
                                            {{ csrf_field() }}


                                            <input type="hidden" name="commentable_type" value="App\Project">
                                            <input type="hidden" name="commentable_id" value="{{$project->id}}">


                                            <div class="form-group">
                                                <label for="comment-content">Comment</label>
                                                <textarea placeholder="Enter comment"
                                                          style="resize: vertical"
                                                          id="comment-content"
                                                          name="body"
                                                          rows="3" spellcheck="false"
                                                          class="form-control autosize-target text-left">


                                                          </textarea>
                                            </div>


                                            <div class="form-group">
                                                <label for="comment-content">Proof of work done (Url/Photos)</label>
                                                <textarea placeholder="Enter url or screenshots"
                                                          style="resize: vertical"
                                                          id="comment-content"
                                                          name="url"
                                                          rows="2" spellcheck="false"
                                                          class="form-control autosize-target text-left">


                                                          </textarea>
                                            </div>


                                            <div class="form-group">
                                                <input type="submit" class="btn btn-primary"
                                                       value="Submit"/>
                                            </div>
                                        </form>
                                        </div>
{{--  --}}


        </div>
        </div>


        <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
          {{-- <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div> --}}
          <div class="sidebar-module">
            <h4>Actions</h4>
            <ol class="list-unstyled">
              <li><a href="/projects/{{$project->id}}/edit">Edit</a></li>
              <li><a href="/projects/create">Add a Project</a></li>
              <li><a href="/projects">View My Projects</a></li>
              <br>

              @if($project->user_id == Auth::user()->id)
              <li>
                <a
             href="#"
                 onclick="
                 var result = confirm('Are you sure you wish to delete this Project?');
                     if( result ){
                             event.preventDefault();
                             document.getElementById('delete-form').submit();
                     }
                         "
                         >
                 Delete
             </a>

             <form id="delete-form" action="{{ route('projects.destroy',[$project->id]) }}"
               method="POST" style="display: none;">
                       <input type="hidden" name="_method" value="delete">
                       {{ csrf_field() }}
             </form>
              </li>

        @endif
              {{-- <li><a href="#">Add User</a></li> --}}
            </ol>
            <hr>
            <h4>Add Members</h4>
            <div class="row">
              <div class="col-lg-1-12 col-md-1-12 col-sm-12">
                <form id="add_user" action="{{ route('projects.adduser') }}"
                  method="POST">
                  {{csrf_field()}}
                <div class="input-group">
                  <input class="form-control" name="project_id" value="{{$project->id}}" type="hidden">
                  <input type="text" class="form-control" name="email" placeholder="Email">
                  <span class="input-group-btn">
                    <button class="btn btn-default" type="submit" name="button"> Add</button>
                  </span>
                </div>
              </form>

              </div>

              </div>

          <hr>
          <h4>Team Members</h4>
          <ol class="list-unstyled">
            @foreach ($project->users as $user)
              <li><a href="#">{{$user->email}}</a</li>
            @endforeach


          </ol>

          {{-- <div class="sidebar-module">
            <h4>Users</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li>
            </ol>
          </div> --}}
        </div>
    @endsection